/**
 * Waterloo OpenData API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * A person instructing a Class
 * @param courseId Course identifier number, not unique
 * @param courseOfferNumber Course offer number identifier for this class
 * @param sessionCode Session code number for this class
 * @param classSection Number identifying the section of this class
 * @param termCode Waterloo academic term code
 * @param instructorRoleCode The code designation for the instructor's role in this class
 * @param instructorFirstName The Instructors preferred first name
 * @param instructorLastName The Instructors preferred last name
 * @param instructorUniqueIdentifier A unique identifier that persists through name changes. Not guaranteed, but likely to be immutable for instructor.
 * @param classMeetingNumber Identifier for the class meeting this instructor is for
 */
data class ClassInstructor (

    /* Course identifier number, not unique */
    val courseId: kotlin.String? = null,
    /* Course offer number identifier for this class */
    val courseOfferNumber: kotlin.Int? = null,
    /* Session code number for this class */
    val sessionCode: kotlin.String? = null,
    /* Number identifying the section of this class */
    val classSection: kotlin.Int? = null,
    /* Waterloo academic term code */
    val termCode: kotlin.String? = null,
    /* The code designation for the instructor's role in this class */
    val instructorRoleCode: kotlin.String? = null,
    /* The Instructors preferred first name */
    val instructorFirstName: kotlin.String? = null,
    /* The Instructors preferred last name */
    val instructorLastName: kotlin.String? = null,
    /* A unique identifier that persists through name changes. Not guaranteed, but likely to be immutable for instructor. */
    val instructorUniqueIdentifier: kotlin.String? = null,
    /* Identifier for the class meeting this instructor is for */
    val classMeetingNumber: kotlin.Int? = null
) {
}