/*
 * Modified to not deserialize dates
 */

/**
 * Waterloo OpenData API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * Data describing scheduling and availability data for a Class
 * @param courseId Course identifier number, not unique
 * @param courseOfferNumber Course offer number identifier for this class
 * @param sessionCode Session code number for this class
 * @param classSection Number identifying the section of this class
 * @param termCode Waterloo academic term code
 * @param classMeetingNumber Identifier for the class meeting this schedule data relates to
 * @param scheduleStartDate The date this schedule begins
 * @param scheduleEndDate The date this schedule ends
 * @param classMeetingStartTime The start time of this class
 * @param classMeetingEndTime The end time of this class
 * @param classMeetingDayPatternCode A code representing the days the class schedule takes place during the week
 * @param classMeetingWeekPatternCode A Y|N per day representation of the class schedule taking place during the week
 * @param locationName Building and room name for the location of this class schedule
 */
data class ClassSchedule (

    /* Course identifier number, not unique */
    val courseId: String? = null,
    /* Course offer number identifier for this class */
    val courseOfferNumber: Int? = null,
    /* Session code number for this class */
    val sessionCode: String? = null,
    /* Number identifying the section of this class */
    val classSection: Int? = null,
    /* Waterloo academic term code */
    val termCode: String? = null,
    /* Identifier for the class meeting this schedule data relates to */
    val classMeetingNumber: Int? = null,
    /* The date this schedule begins */
    val scheduleStartDate: String? = null,
    /* The date this schedule ends */
    val scheduleEndDate: String? = null,
    /* The start time of this class */
    val classMeetingStartTime: String? = null,
    /* The end time of this class */
    val classMeetingEndTime: String? = null,
    /* A code representing the days the class schedule takes place during the week */
    val classMeetingDayPatternCode: String? = null,
    /* A Y|N per day representation of the class schedule taking place during the week */
    val classMeetingWeekPatternCode: String? = null,
    /* Building and room name for the location of this class schedule */
    val locationName: String? = null
) {
}